### ISSUE TITLE
Request: Press "home" key to return to top of feed

### ISSUE THREAD

**Issue by SpencerDub** [ssbc/patchwork#1093] opened 2019-06-13 00:24 UTC
This is a very, very minor feature request.

It would be super convenient if, when browsing the feed, pressing the "home" key on the keyboard would scroll to the top of the feed. This is fairly standard UX behavior in web browsers, so it catches me by surprise when I try to do it in Patchwork and it doesn't work.

**Comment by black-puppydog** [comment] 2019-06-14 06:04
It actually does work (for me, running on Linux) but the problem is that most of the time the feed is not the "active" UI element. For me it only works once I click somewhere on a post or the empty space around. 

This is also true for navigating down/up with Space/Shift-Space and PageDown/Pageup, and that has been something I've been noticing too.

**Comment by black-puppydog** [comment] 2019-06-14 06:06
This seems to happen every time we change the main view. (Sorry, I don't know the right web vocab here. The area that actually shows all the stuff).
It is most visible when navigating via the search bar. It keeps the focus, so if you hit the keyboard you just start typing there instead of scrolling.

**Comment by Powersource** [comment] 2019-06-16 20:58
(essentially) a duplicate of https://github.com/ssbc/patchwork/issues/793

**Closed by Powersource** 2019-06-16 20:58 UTC
Labels: topic:UX & UI, type:enhancement
