### ISSUE TITLE
Unexpected crash

### ISSUE THREAD

**Issue by niceking** [ssbc/patchwork#188] opened 2015-12-13 21:37 UTC
<img width="418" alt="screen shot 2015-12-10 at 9 05 01 pm" src="https://cloud.githubusercontent.com/assets/4241125/11769531/599f98c8-a24e-11e5-9b4b-2272c38f065b.png">

Running Patchwork Version 0.34.2 on OSX 10.11.1

**Comment by pfraze** [comment] 2015-12-13 21:41
Closing as a duplicate of https://github.com/ssbc/patchwork/issues/111

Thank you for reporting!

**Closed by pfraze** 2015-12-13 21:41 UTC
