### ISSUE TITLE
Unexpected Error: Cannot read property 'focus' of undefined

### ISSUE THREAD

**Issue by cryptix** [ssbc/patchwork#118] opened 2015-11-24 11:03 UTC
```
Cannot read property 'focus' of undefined

TypeError: Cannot read property 'focus' of undefined
    at [object Object].module.exports.React.createClass.focusContent (/Users/hnry/patchwork/node_modules/react-modal/lib/components/ModalPortal.js:122:22)
    at [object Object].module.exports.React.createClass.componentDidUpdate (/Users/hnry/patchwork/node_modules/react-modal/lib/components/ModalPortal.js:95:12)
    at CallbackQueue.assign.notifyAll (/Users/hnry/patchwork/node_modules/react/lib/CallbackQueue.js:65:22)
    at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/Users/hnry/patchwork/node_modules/react/lib/ReactReconcileTransaction.js:81:26)
    at ReactReconcileTransaction.Mixin.closeAll (/Users/hnry/patchwork/node_modules/react/lib/Transaction.js:202:25)
    at ReactReconcileTransaction.Mixin.perform (/Users/hnry/patchwork/node_modules/react/lib/Transaction.js:149:16)
    at ReactUpdatesFlushTransaction.Mixin.perform (/Users/hnry/patchwork/node_modules/react/lib/Transaction.js:136:20)
    at ReactUpdatesFlushTransaction.assign.perform (/Users/hnry/patchwork/node_modules/react/lib/ReactUpdates.js:86:38)
    at flushBatchedUpdates (/Users/hnry/patchwork/node_modules/react/lib/ReactUpdates.js:147:19)
    at wrapper (/Users/hnry/patchwork/node_modules/react/lib/ReactPerf.js:66:21)
```

This was an unhandled exception.

**Comment by pfraze** [comment] 2015-11-24 16:55
Closing as a duplicate of https://github.com/ssbc/patchwork/issues/116

**Closed by pfraze** 2015-11-24 16:55 UTC
