### ISSUE TITLE
crash: [Error: cb called twice from local api]

### ISSUE THREAD

**Issue by keks** [ssbc/patchwork#321] opened 2016-03-05 22:25 UTC
I was just browsing around patchwork and then it crashed. Restarting results in the same crash. No more patchwork for me :cry:.

You can find [npm-debug.log](https://github.com/ssbc/patchwork/files/160074/npm-debug.log.txt) attached. But its named `npm-debug.log.txt`, because Github doesn't like files that end with `.log`.

```
...
  "Feeds updated: 1, New messages: 1"
[Error: cb called twice from local api]

npm ERR! Linux 4.3.3-3-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v5.7.0
npm ERR! npm  v3.7.5
npm ERR! code ELIFECYCLE
npm ERR! ssb-patchwork@2.6.1 start: `node ./index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ssb-patchwork@2.6.1 start script 'node ./index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ssb-patchwork package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ssb-patchwork
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ssb-patchwork
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/keks/src/patchwork/npm-debug.log
```

**Comment by keks** [comment] 2016-03-05 22:59
It crashes when first loading `localhost:7777`, not automatically when starting patchwork. This is the new [npm-debug.log](https://github.com/ssbc/patchwork/files/160086/npm-debug.log.txt).
.

**Comment by dominictarr** [comment] 2016-03-06 00:54
@keks so scuttlebot still works normally? this is only patchwork?

@pfraze the bit that truncates the error message is a makes things like this quite hard to debug. we should find a way to only enable that when it's a error from the input validation.

**Comment by keks** [comment] 2016-03-06 00:55
Yep, sbot works fine.

**Comment by dominictarr** [comment] 2016-03-06 00:57
how are did you install patchwork? was it via git or npm or a deb bundle?

**Comment by keks** [comment] 2016-03-06 00:58
via git. I'm on master.

**Comment by dominictarr** [comment] 2016-03-06 02:13
since this is only happening on your machine this seems pretty hard to debug.

The first thing, I think is try installing this PR https://github.com/ssbc/muxrpcli/pull/4 as you version muxrpcli of. the easiest is to clone it into your dev directory, then link to it from patchwork's node_modules directory. that will give us a stacktrace, at least.

maybe it's something in your database, in which case you might have to send us a copy of that. (sending us the database but not the `secret` file) since encrypted messages are stored encrypted, it wouldn't tell us their content, although the metadata would be revealed, because the recipients are indexed. (when we reimplement the secure-scuttlebutt indexes as streamviews this will be fixed, it will be easy to send us the db without the indexes, so much less privacy leakage)

**Comment by dominictarr** [comment] 2016-03-06 02:13
but, lets try that second, first lets just get the stacktrace. I'd also try reverting back to an earlier version of patchwork, because you never know.

**Comment by dominictarr** [comment] 2016-03-06 06:06
@keks also, you could try this to confirm if it's really a patchwork problem: https://github.com/dominictarr/patchdeck

**Comment by keks** [comment] 2016-03-06 12:48
Okay, I'm in my stupid university network so I can't install anything that depends on `git://`... for some reason it doesn't even work through VPN.

I tried downgrading to 2.6.0, but the problem persisted. Then I tried installing patchdeck but that failed due to git:// reasons (eccjs again).

I will try to do the muxrpc thing now.

**Comment by keks** [comment] 2016-03-06 12:57
I think I did the muxrpc thing, but nothing changed.

```
~/src $ git clone https://github.com/ssbc/muxrpcli
~/src $ cd muxrpcli
~/src/muxrpcli $ git pull origin betteroutthanin
~/src/muxrpcli $ npm install
~/src/muxrpcli $ cd ../patchwork/node_modules
~/src/patchwork/node_modules $ mv muxrpcli muxprcli-bak
~/src/patchwork/node_modules $ ln -s ~/src/muxrpcli
~/src/patchwork/node_modules $ cd ..
~/src/patchwork/node_modules $ npm start
```

Same error, and no stack trace. What did I miss?

**Comment by keks** [comment] 2016-03-06 13:22
I didn't really know where to put 400MB so you can netcat it under 188.166.27.32 port 8080. SHA1 is c63ce8ca3602e7fa342cc2e96bce90379dbbca35.

**Comment by cryptix** [comment] 2016-03-06 16:32
re eccjs: ssbc/ssb-keys#22. I hope that's merged soon.

@keks: I think you can drop `.ssb/blobs` from the backup next time.

btw: I got another sha1 (`cf427f94a91a64cfd9ca5860e721dafd6f90e189`) but it is a valid tar file.

**Comment by keks** [comment] 2016-03-06 16:34
okay I belive my socat magic failed. hang on...

**Comment by pfraze** [comment] 2016-03-06 17:45
@keks I downloaded your dataset and didnt experience the crash, but you also (correctly) did not include your keys, and so it wasn't a perfect reproduction.

@dominictarr I dont think muxrpcli is the code that's dumping that error. So, using the new muxrpcli wont help us here. I'm not sure, yet, where that's done.

@keks I'm going to brainstorm and poke around at some things, will update you in a bit.

**Comment by pfraze** [comment] 2016-03-06 18:00
May be related to https://github.com/ssbc/patchwork/issues/312

**Comment by pfraze** [comment] 2016-03-06 18:17
@keks latest on master should now cause the stack trace to output. Can you pull and capture that trace for us?

**Comment by keks** [comment] 2016-03-06 18:19
```
Error: cb called twice from local api
    at /home/keks/src/patchwork/node_modules/packet-stream/index.js:150:24
    at /home/keks/src/patchwork/node_modules/muxrpc/stream.js:41:22
    at done (/home/keks/src/patchwork/node_modules/secure-scuttlebutt/index.js:524:7)
    at /home/keks/src/patchwork/node_modules/secure-scuttlebutt/index.js:502:9
    at /home/keks/src/patchwork/node_modules/secure-scuttlebutt/node_modules/pull-stream/maybe.js:41:9
    at /home/keks/src/patchwork/node_modules/secure-scuttlebutt/node_modules/pull-stream/sinks.js:11:20
    at drain (/home/keks/src/patchwork/node_modules/pull-paramap/index.js:26:11)
    at /home/keks/src/patchwork/node_modules/pull-paramap/index.js:65:7
    at next (/home/keks/src/patchwork/node_modules/secure-scuttlebutt/node_modules/pull-stream/sinks.js:7:7)
    at /home/keks/src/patchwork/node_modules/secure-scuttlebutt/node_modules/pull-stream/sinks.js:20:11
```

**Comment by pfraze** [comment] 2016-03-06 18:58
```
    at done (/home/keks/src/patchwork/node_modules/secure-scuttlebutt/index.js:524:7)
```

That's the end of a `relatedMessages` call. I suspect this is an edgecase somewhere inside of `patchwork-threads`.

**Comment by keks** [comment] 2016-03-06 20:12
Heads Up: I tried getting patchdeck to work but I just get a white screen in electron.

**Comment by clehner** [comment] 2016-03-06 20:16
@keks it seems that [electro](https://github.com/dominictarr/electro) eats electron's stack traces. Try running `node .` in patchdeck and then install dependencies until the dependency-related errors go away. (I've opened PRs for those now)

**Comment by pfraze** [comment] 2016-03-06 20:35
Let's confirm some facts:

 - The crash is occurring in the backend thread, not the frontend (ui) thread
 - The crash occurs when the UI is loaded
 - Based on the stack-trace, it *appears* the crash occurs after a `ssb.relatedMessages` call.

I'm finding that `relatedMessages` is only used in `getPostThread`, which doesnt get called until you open a thread.

@keks what happens if you go to http://localhost:7777/#/activity or http://localhost:7777/#/contacts ?

**Comment by keks** [comment] 2016-03-06 20:39
Okay crap. Now I can't reproduce anymore.

I was on /#/data all the time and it kept crashing. After restarting I simply reloaded. So this time I was going to /#/contacts instead, and it loaded. Clicked Activity feed, still no crash. It doesn't even crash on the data feed anymore. Strange.

**Comment by pfraze** [comment] 2016-03-06 20:44
@keks what about the inbox view?

**Comment by keks** [comment] 2016-03-06 20:45
It works. Everything does.

**Comment by pfraze** [comment] 2016-03-06 20:49
OK. I'd bet money this was caused by a message that wasn't downloaded yet, causing some thread-handling code to trip up. That would explain why it's fixed, again: the missing message could've downloaded.

@keks just to triple-check, previously this crash occurred when you opened `localhost:7777/` (not some other page) and required no other action, like click on a thread, correct?

**Comment by keks** [comment] 2016-03-06 20:50
Nope, I was on /#/data.

**Comment by pfraze** [comment] 2016-03-06 20:52
@keks you mean the crash error only ever occurred on `#/data` ?

**Comment by keks** [comment] 2016-03-06 20:54
I'm not sure, I *believe* I only tested it using `/#/data`. (I simply hit reload after restarting patchwork). Maybe I was on `/` in a different tab in between, I am not sure (but I don't think so).

In between attempts I was running sbot server though (for quite a while sometimes), so messages should have downloaded in the mean time.

**Comment by pfraze** [comment] 2016-03-06 20:56
Ok. Let's leave this issue open and be aware, this is likely an active issue we need to root out.

> In between attempts I was running sbot server though (for quite a while sometimes), so messages should have downloaded in the mean time.

Rate-limiting could cause this to occur, and take a while to solve. (We're in the process of fixing that.)

**Comment by wanderer** [comment] 2016-03-19 17:27
I'm getting this error to. I'm using latest on master. It crashes this way every time I go to http://localhost:7777/#/msg/%25zeL2NSWnYHRql3dMaRPU04YhjKCtHNv4CXH9CirfZso%3D.sha256

**Comment by wanderer** [comment] 2016-03-19 17:33
oh its happen when you have a message in a thread but don't have the root message in a thread. I can view [this message](http://localhost:7777/#/msg/%25neukrdVbttqZBp7%2FvKA2UVyZh9bMkuTnbPnQ2a3CqTw%3D.sha256) from @pfraze but when I click on "View the full discussion" it crashes. Can someone tell me who posted the original message? I want to follow them and see if it will stop crashing.

**Comment by pfraze** [comment] 2016-03-19 17:45
Humm, I'll try to build a test-case around this. The original message was by dust, `@/02iw6SFEPIHl8nMkYSwcCgRWxiG6VP547Wcp1NW8Bo=.ed25519`

**Comment by wanderer** [comment] 2016-03-19 18:15
weird im following dust

**Comment by pfraze** [comment] 2016-03-31 16:36
I think I found the bug!!!!!!!!!!

https://github.com/ssbc/secure-scuttlebutt/pull/146

**Comment by ahdinosaur** [comment] 2017-03-16 12:37
closing since stale?

**Closed by ahdinosaur** 2017-03-16 12:37 UTC
Labels: bug
