### ISSUE TITLE
The Appimage client for aarch64 does not work on Manjaro-arm

### ISSUE THREAD

**Issue by FoundOne** [ssbc/patchwork#1377] opened 2021-01-19 09:18 UTC
It just opens a blank window. Here is the tail of the error log:
```
error loading sodium bindings: No native build was found for platform=linux arch=arm64 runtime=electron abi=73 uv=1 armv=8 libc=glibc
falling back to javascript version.
git-ssb is not installed, or not available in path
ssb-friends: stream legacy api used
Error: /tmp/.org.chromium.Chromium.2Ie5zf: Ð½Ðµ Ð¼Ð¾Ð¶Ðµ Ð´Ð° ÑÐµ Ð¾ÑÐ²Ð¾ÑÐ¸ ÑÐ°Ð¹Ð»ÑÑ ÑÑÑ ÑÐ¿Ð¾Ð´ÐµÐ»ÐµÐ½Ð¸Ñ Ð¾Ð±ÐµÐºÑ: ÐÑÐ¼Ð° ÑÐ°ÐºÑÐ² ÑÐ°Ð¹Ð» Ð¸Ð»Ð¸ Ð´Ð¸ÑÐµÐºÑÐ¾ÑÐ¸Ñ
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/tmp/.mount_PatchwUsvKBp/resources/app.asar/node_modules/@felixrieseberg/spellchecker/lib/spellchecker.js:3:16)
(node:6179) UnhandledPromiseRejectionWarning: Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at WebFrame.<computed> (/tmp/.mount_PatchwUsvKBp/resources/electron.asar/renderer/api/web-frame.js:64:33)
    at WebFrame.executeJavaScript (/tmp/.mount_PatchwUsvKBp/resources/electron.asar/common/api/deprecate.js:114:32)
    at /tmp/.mount_PatchwUsvKBp/resources/electron.asar/renderer/web-frame-init.js:11:43
    at /tmp/.mount_PatchwUsvKBp/resources/electron.asar/renderer/ipc-renderer-internal-utils.js:7:40
    at new Promise (<anonymous>)
    at EventEmitter.<anonymous> (/tmp/.mount_PatchwUsvKBp/resources/electron.asar/renderer/ipc-renderer-internal-utils.js:7:9)
    at EventEmitter.emit (events.js:200:13)
    at Object.onMessage (/tmp/.mount_PatchwUsvKBp/resources/electron.asar/renderer/init.js:42:16)
(node:6179) UnhandledPromiseRejectionWarning: Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at WebFrame.<computed> (/tmp/.mount_PatchwUsvKBp/resources/electron.asar/renderer/api/web-frame.js:64:33)
    at WebFrame.executeJavaScript (/tmp/.mount_PatchwUsvKBp/resources/electron.asar/common/api/deprecate.js:114:32)
    at /tmp/.mount_PatchwUsvKBp/resources/electron.asar/renderer/web-frame-init.js:11:43
    at /tmp/.mount_PatchwUsvKBp/resources/electron.asar/renderer/ipc-renderer-internal-utils.js:7:40
    at new Promise (<anonymous>)
    at EventEmitter.<anonymous> (/tmp/.mount_PatchwUsvKBp/resources/electron.asar/renderer/ipc-renderer-internal-utils.js:7:9)
    at EventEmitter.emit (events.js:200:13)
    at Object.onMessage (/tmp/.mount_PatchwUsvKBp/resources/electron.asar/renderer/init.js:42:16)
(node:6179) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6179) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6179) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6179) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
By what I see it says it can't find libsodium, but I'm pretty sure I have it. Even one of my other apps depends on it. `yay -Qs libsodium` says `local/libsodium 1.0.18-2`. Also I'd be happy to have an AUR package for aarch64. The the binary package is just for x86_64 and the git version is outdated (it fails to compile).

My platform is River (wayland), Manjaro-arm rk3399 (Pinebook Pro)

**Comment by black-puppydog** [comment] 2021-01-19 12:28
@FoundOne just to clarify: is this the appimage of the latest stable release (v3.18.0), or the beta release (v3.18.1-beta-1) or are you running from master?

If this is *not* the stable AppImage, then this is a known issue (#1324) and will have to be fixed or reverted before the next stable version.

**Comment by FoundOne** [comment] 2021-01-19 12:40
I just got the last appimage from the releases. It's v3.18.0. I haven't tried to build form master.

**Comment by black-puppydog** [comment] 2021-01-19 12:43
Okay, then I'll close this as a duplicate of #1324. Feel free to comment there of course. :)

**Closed by black-puppydog** 2021-01-19 12:43 UTC
