### ISSUE TITLE
Patchwork stuck [initial replication progress]

### ISSUE THREAD

**Issue by mixmix** [ssbc/patchwork#605] opened 2017-08-10 05:47 UTC
looks like it stalls out at 98%

mix has seen this a bunch when trying to onboarding while on same wifi as another person. No idea if that's a factor. didn't have them use a pub invite too, though after some local replication, new peer discovers remote pubs and starting talking... 

rumour that e.b.t. could fix this.

**Comment by jeremytregunna** [comment] 2017-08-21 18:33
@mixmix I'm having this same problem, and i'm the only user on my network. Started for me 3 days ago, have been unable to get online since.

**Comment by mixmix** [comment] 2017-08-22 20:29
Jeremy did you manage to join a pub? Do you see a progress bar not
completing? what do you mean by "haven't been online since". Since what
exactly (what was the prior stage for you?)
Have you closed and opened patchwork

**Comment by jeremytregunna** [comment] 2017-08-22 20:31
@mixmix I see pubs coming and going, I get a lot that are not reachable, but some that are. I've closed and opened it many many times. What I mean "haven't been online since" is the UI isn't usable, since all I see are spinners everywhere, making it impossible to use Patchwork. Still ongoing problem as of today. Tried 3.6.3 up to 3.6.6.

**Comment by jeremytregunna** [comment] 2017-08-22 20:44
@mixmix here's a screenshot of what it's been doing for days (and I have restarted more than I care to admit hoping that "this time it'll work" heh) http://jer.tregunna.ca/7KPvjP

**Comment by jeremytregunna** [comment] 2017-08-22 23:17
@mixmix Got tired and tried something; have another machine with 3.6.3 on it, copied the .ssb from that machine back to my main machine where this was happening, fired up 3.6.5 on it. Upgraded DB, downloaded and indexed, and all is fine. At least gets me going again, but not sure what got it stuck. I still have the misbehaving version around if I can try anything.

**Comment by jnny** [comment] 2017-10-09 22:08
also been having this issue on and off for weeks. deleting just .ssb/flume directory and allowing it to be rebuilt upon initial reboot seems to do the trick.

**Comment by mixmix** [comment] 2017-10-09 22:37
@jeremytregunna thanks for the updates.

thanks for also posting @jnny 

there is a fix in 3.7.1 - https://github.com/ssbc/patchwork/releases which may help. Note this fix will only come through with the installer (I think). If you're pulling the git repo you need (I think) node 8 and you'll have to rebuild (`npm run rebuild`) to use latest electron.

@mmckegg can you tweak the README and maybe the package.json with node versions needed?

**Comment by mmckegg** [comment] 2017-10-09 23:19
@mixmix Node version doesn't matter. Only the electron version and that is already in the package.json.

**Comment by mmckegg** [comment] 2017-10-18 11:57
I think this issue could be caused by a few things:

- If it never finishes loading then it might be a a corrupt flume log (a bug was recently fixed in relation to that): https://github.com/ssbc/scuttlebot/issues/427
- If patchwork seems to work file but messages never finish downloading then it might be this that was also recently fixed: https://github.com/ssbc/scuttlebot/pull/444
- Then there was the old locking bug that was fixed in the last release by upgrading to the latest version of electron.

All of the above have now been fixed and included in the next release. I'm going to close this bug, but if you get this again, please feel free to reopen!

**Closed by mmckegg** 2017-10-18 11:57 UTC
