### ISSUE TITLE
version recommendations

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#613] opened 2017-08-23 04:12 UTC
I noticed that 3.6.6 had a warning suggesting to use 3.6.5 and 3.6.5 had a warning suggesting to use 3.6.6

this does not make sense, so I changed both to suggest using 3.6.4. If this is wrong, we can change it.

**Comment by mmckegg** [comment] 2017-08-25 11:51
THERE IS NO TRUTH!

**Comment by mmckegg** [comment] 2017-08-25 11:53
Every version is broken in its own special unique way.

I'm still in favour of "recommending" 3.6.6

**Comment by mmckegg** [comment] 2017-09-14 02:33
@dominictarr 

We really need to figure out how to fix Patchwork so that it doesn't have [this problem](https://github.com/ssbc/patchwork/issues/597).

I have some guesses about what is going on. It seems to be something in sbot. Might have been surfaced by a recent node update. I think it has always been here, just some recent changes to patchwork made it more obvious (depending on a current connection to sbot for clicking links, and scrolling the feed).

We could possibly hack around it in the user interface, but would be nice if we could just fix the damn issue. Will try and create a local testcase (on testnet) that contains the issue and can reproduce. Would this be helpful?

Or should we just turn on ebt and be done with it? Could experiment with only running legacy gossip in non permanent mode, and only have permanent connections for ebt.

**Comment by dominictarr** [comment] 2017-09-26 05:18
> THERE IS NO TRUTH!

I agree! but at least this new lie makes more sense than the old one.

We can't enable EBT just yet, because initial sync performance is too slow,
(but I'm working on that! see validate2 branch on secure-scuttlebutt)

**Comment by ahdinosaur** [comment] 2017-09-29 03:26
> I noticed that 3.6.6 had a warning suggesting to use 3.6.5 and 3.6.5 had a warning suggesting to use 3.6.6

the reason i did this was to emphasize that no version is perfect, everything has trade-offs. i'm not sure how recommending 3.6.4 is a better lie, it has the same problems as 3.6.5 right? there really is no clear version to recommend, both Matt and i think we should recommend 3.6.6, but Mix felt strongly that we should _not_ recommend 3.6.6.

**Comment by mmckegg** [comment] 2017-09-29 03:37
I think 3.6.6 might actually have some big onboarding bugs in it right now! Just about to investigate this.

**Comment by mmckegg** [comment] 2017-09-30 03:53
Just about to release 3.7.0!

It looks like upgrading electron to 1.8.1 has fixed the locking bugs! Gonna stamp out a new release shortly. We can (probably) go back to recommending the latest version again after this!

**Comment by ahdinosaur** [comment] 2017-10-16 04:19
[`3.7.1` has been released](https://github.com/ssbc/patchwork/releases/tag/v3.7.1)! so since we now recommend [the latest version of Patchwork](https://github.com/ssbc/patchwork/releases/latest), i'm closing this issue.

**Closed by ahdinosaur** 2017-10-16 04:19 UTC
