### ISSUE TITLE
yet another infinite loop

### ISSUE THREAD

**Issue by bhaugen** [ssbc/patchwork#687] opened 2017-12-09 12:50 UTC
Tried to post this in patchwork, didn't seem to work, just faded out:
Let's see if I can post while infinitely scuttling...started in this thread:
%atI0+2VrTnCN3zDT9M1dNunt4OvRcWcQ6wHydgeWmH8=.sha256
and then this thread:
%r4jJxssgEeSf6BvXCtUNMdqGftEcBzSUQM9uDDllQFM=.sha256

The first one says, 
> I'm tripple commenting, but one of them was a nested comment - it's not my fault if your client doesn't support it yet  :see_no_evil:

**Comment by mmckegg** [comment] 2017-12-12 20:31
@bhaugen 

Are you still getting issues like this? Normally when this happens it is because an unhandled error occurred. Do you have any console output?

**Comment by bhaugen** [comment] 2017-12-12 20:45
I have not seen that problem since moving to Patchwork-3.8.3-linux-x86_64.AppImage

As far as I am concerned, you can close this issue. If I see anything like that again, I'll either re-open it or raise a new one and will try to get more evidence.

**Comment by matthiasbeyer** [comment] 2017-12-12 20:49
I get something like this with the following console output:

```
TypeError: Cannot read property 'content' of undefined
    at api.sbot.async.get (/home/m/archive/development/track/patchwork/modules/feed/html/rollup.js:285:27)
    at /home/m/archive/development/track/patchwork/node_modules/patchcore/sbot.js:146:31
    at Object._requests.(anonymous function) (/home/m/archive/development/track/patchwork/node_modules/packet-stream/index.js:38:5)
    at PacketStream._onrequest (/home/m/archive/development/track/patchwork/node_modules/packet-stream/index.js:151:26)
    at PacketStream.write (/home/m/archive/development/track/patchwork/node_modules/packet-stream/index.js:134:41)
    at /home/m/archive/development/track/patchwork/node_modules/muxrpc/pull-weird.js:56:15
    at /home/m/archive/development/track/patchwork/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/m/archive/development/track/patchwork/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/home/m/archive/development/track/patchwork/node_modules/packet-stream-codec/index.js:111:11)
    at drain (/home/m/archive/development/track/patchwork/node_modules/pull-reader/index.js:39:14)
```

hope that helps.

**Comment by mmckegg** [comment] 2017-12-12 21:11
@matthiasbeyer yes! Thank you that is very helpful!

Pretty sure I have [squished that particular bug now](https://github.com/ssbc/patchwork/commit/f6487e3f937bcb47dc60546afcec2e728660b0db). In this case it was a race condition caused by receiving posts out of order (a reply before the root post) and not checking to make sure the root was actually present.

**Comment by mmckegg** [comment] 2017-12-12 21:13
I'm gonna close this issue for now. Feel free to create more issues if similar infinite loading bugs are discovered!

**Closed by mmckegg** 2017-12-12 21:13 UTC
