### ISSUE TITLE
Exif data removal, feature? 

### ISSUE THREAD

**Issue by wwwhtml** [ssbc/patchwork#1022] opened 2019-05-05 22:43 UTC
Hi SSBC-Patchwork Folks,

First please excuse me if this is not the best avenue to suggest a feature, but I couldn't see any other place in the short search I did. I am in a hurry at this time, but I wanted to share this before I forget.

Anyhow,  I have noticed that photos uploaded in Patchwork still have their exif data, is the exif data removal from images something that is already in your plans?  If not, I feel it would be a nice feature to have, if possible.

Many thanks for you time reading this.

Daniel

**Comment by christianbundy** [comment] 2019-05-06 00:36
Hey Daniel!

> Anyhow, I have noticed that photos uploaded in Patchwork still have their exif data

Could you confirm which version of Patchwork this is happening on (and maybe your operating system)? I think this should have been resolved in 3.11.5, so it would be concerning to hear that this isn't working correctly. Thanks for opening this issue!

**Comment by wwwhtml** [comment] 2019-05-10 10:20
Hey Christian, the version I am using is: 3.11.6 (3.11.6).

I just ran another test, on an image of someone else, and the exif data shows up. 
The image was uploaded 9 months ago. I have an screenshot to show you, if you want to see it.

A second test that I just did was to upload and image I found online, and run the exif data check before and after I uploaded to ssb and the data still there.

**Comment by wwwhtml** [comment] 2019-05-10 10:32
Not sure if this  "&qyRiKeFlm4njLbrVB3/6ZrYQyNjvj8W0jH09XJ7EYp4=.sha256" is searchable. But it is of the test image I uploaded a moment ago and it shows its exif data as well.

**Comment by christianbundy** [comment] 2019-05-10 14:17
Confirmed, it looks like the EXIF metadata removal isn't working correctly. I've opened an issue upstream: https://github.com/ssbc/ssb-blob-files/issues/6

Thanks a bunch for reporting this, it doesn't look like we would have found it any other way.

**Comment by wwwhtml** [comment] 2019-05-11 02:16
Glad to be of some help. 
(My second time finding that needed fix.)

**Comment by wwwhtml** [comment] 2019-05-11 06:06
@christianbundy, I installed the new beta version that you announced some 7 or so hours ago, 3.12.0-Beta-2, and check for the bug.  Unfortunately the bug is still there.  

&V3H2IbozqHVnT6bVDmpMirH7KrL9Ck2d6JQFg9/PkcY=.sha256

I am wondering if this is just happening on MacOS. Because I asked someone else to check one of the previous images and his posted results doesn't show the data. Just guessing.

Thanks.

**Comment by christianbundy** [comment] 2019-05-11 14:51
Sorry for closing this without actually testing to ensure it was fixed in Patchwork, I was so certain that I understood why it wasn't working but I should have double-checked. I'll create another issue in the ssb-blob-files repo and hope we can figure out what's going on.

**Comment by arj03** [comment] 2019-05-11 15:15
For removing exif we use [piexifjs](https://github.com/hMatoba/piexifjs) which sadly only works on [jpg](https://github.com/hMatoba/piexifjs/issues/28). So whatever metadata is embedded in the image must be something else than exif.

**Comment by wwwhtml** [comment] 2019-05-13 03:05
I suggest that, until the png data can be extracted, it should be warning message for those uploading photos/images; so they are aware.

**Comment by christianbundy** [comment] 2019-05-13 03:42
@wwwhtml 

That sounds neat, I'd love to merge a pull request for that. If you don't have time I'd love if you could open an issue as a feature request, maybe enumerating all of the places that this would need to happen? I know about the message composer and the profile photo chooser (for yourself and others), but there may be other places where we'd need this warning.

**Closed** 2019-05-13 03:42 UTC
Labels: bug

**Comment by wwwhtml** [comment] 2019-05-16 08:55
@christianbundy 

I feel that we should get request rolling, and keep it open for others to add more areas where the warming should come up.  -I haven't look into what other areas need that warning, but the ones you listed it is a good start.

**Comment by christianbundy** [comment] 2019-05-16 15:36
I don't have bandwidth for that at the moment, but I'm happy to support someone else working on it if you need any input from me.

**Comment by christianbundy** [comment] 2019-05-16 15:38
Oops, I didn't see #1042, thanks for opening!
