### ISSUE TITLE
Unexpected Error: Invariant Violation ... 

### ISSUE THREAD

**Issue by cryptix** [ssbc/patchwork#119] opened 2015-11-24 11:05 UTC
```
Invariant Violation: findComponentRoot(..., .2.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.

Error: Invariant Violation: findComponentRoot(..., .2.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.
    at invariant (/Users/hnry/patchwork/node_modules/fbjs/lib/invariant.js:39:15)
    at Object.ReactMount.findComponentRoot (/Users/hnry/patchwork/node_modules/react/lib/ReactMount.js:764:54)
    at Object.ReactMount.findReactNodeByID (/Users/hnry/patchwork/node_modules/react/lib/ReactMount.js:679:23)
    at Object.getNode (/Users/hnry/patchwork/node_modules/react/lib/ReactMount.js:162:32)
    at ReactDOMComponent.Mixin.getPublicInstance (/Users/hnry/patchwork/node_modules/react/lib/ReactDOMComponent.js:925:29)
    at Object.ReactOwner.removeComponentAsRefFrom (/Users/hnry/patchwork/node_modules/react/lib/ReactOwner.js:84:59)
    at detachRef (/Users/hnry/patchwork/node_modules/react/lib/ReactRef.js:32:16)
    at Object.ReactRef.detachRefs (/Users/hnry/patchwork/node_modules/react/lib/ReactRef.js:74:5)
    at Object.ReactReconciler.unmountComponent (/Users/hnry/patchwork/node_modules/react/lib/ReactReconciler.js:51:14)
    at Object.ReactChildReconciler.updateChildren (/Users/hnry/patchwork/node_modules/react/lib/ReactChildReconciler.js:98:25)
```
This was an unhandled exception.

**Comment by pfraze** [comment] 2015-11-24 16:54
Closing as a duplicate of https://github.com/ssbc/patchwork/issues/116

**Closed by pfraze** 2015-11-24 16:54 UTC
