### ISSUE TITLE
markdown renderer doesn't handle paretheses in urls correctly

### ISSUE THREAD

**Issue by masukomi** [ssbc/patchwork#751] opened 2018-03-25 16:22 UTC
I just tried to link to `https://en.wikipedia.org/wiki/The_Humans_(play)` with `[The Humans](https://en.wikipedia.org/wiki/The_Humans_(play))`

The result was that the paren at the end of the url was misinterpreted as the end of the link parens and NOT the end of the url. This resulted in a broken url and a spare trailing paren being displayed.

I'm suggesting this is a bug because according to the [Common Mark Spec](http://spec.commonmark.org/0.15/) 

> A link destination consists of either
> 
>    a sequence of zero or more characters between an opening < and a closing > that contains no line breaks or unescaped < or > characters, or
>
>    a nonempty sequence of characters that does not include ASCII space or control characters, and includes parentheses only if (a) they are backslash-escaped or (b) they are part of a balanced pair of unescaped parentheses that is not itself inside a balanced pair of unescaped paretheses.

I think this falls under the case of "b" but the sentence is a bit ambiguous.

**Comment by mmckegg** [comment] 2018-04-06 12:32
@masukomi 

I believe this is being handled by [ssbc's fork](https://github.com/ssbc/marked) of [marked](https://github.com/markedjs/marked).

Maybe there are some new changes that need pulling in?

**Comment by christianbundy** [comment] 2018-08-01 01:01
Yeah, here's what I'm seeing with Marked on the CLI:

```console
$ marked
[Cannabis in Georgia](https://en.wikipedia.org/wiki/Cannabis_in_Georgia_(country))
<p><a href="https://en.wikipedia.org/wiki/Cannabis_in_Georgia_(country)">Cannabis in Georgia</a></p>
```

I noticed this at %uRTrki6RVyeTmjMvd421M0nfbVlYYkiVfkfnGBLfIqY=.sha256 but didn't realize it'd already been reported.

**Comment by joeyh** [comment] 2018-11-03 16:53
Reproduced with patchwork 3.11.3, Linux appimage.

**Comment by christianbundy** [comment] 2018-11-03 16:55
This depends on https://github.com/ssbc/ssb-markdown/pull/24, just waiting on that and I'll make a PR to upgrade Patchwork's dependency.

**Comment by mmckegg** [comment] 2018-12-04 00:39
This seems to be fixed with the new markdown-it update, and will be in the next release. Closing!

**Closed by mmckegg** 2018-12-04 00:39 UTC
Labels: bug
