### ISSUE TITLE
Improve feed load times

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#74] opened 2015-11-07 07:55 UTC
I'm trying to figure out why loading that view would be so slow? it's strange because opening the main feed is fast, but opening the posts of a single author is slow. clue: it's fast for someone hasn't posted much, but noticably slower if they have posted lots...

For either me or @pfraze our posts load about 2 seconds on my computer (spinning harddrive)
but for substack it's noticably quicker, but still slower than someone who has only posted a few posts.

I did some investigation, of course I don't know that code very well, but I added a bunch of logging statements, and it looks like on the main feed it calls relatedMessages about 30 times (roughly a page and a half of logging messages) but on one user feed calls relatedMessages about 30 pages worth logging messages! It looks like it might be reading ALL the messages a given user has posted.

**Comment by dominictarr** [comment] 2015-11-07 08:13
Oh, also since we now we have flat threads and they all point to root we don't need to use `relatedMessages` we can just use `links({dest: msg, rel: 'root', source: '%', values: true})` and it will do that only once, instead of doing that for again for each message.

**Comment by pfraze** [comment] 2015-11-07 14:51
>  but on one user feed calls relatedMessages about 30 pages worth logging messages! It looks like it might be reading ALL the messages a given user has posted.

Ah good find, I'll investigate that.

> we can just use links

I need the votes on the replies.

**Comment by pfraze** [comment] 2015-11-07 18:38
Easy fix. Here's what's going on in the codebase.

There's an oversized component, [msg-list](https://github.com/ssbc/patchwork/blob/86452344896ffa0c41f1d908e06b08b1ac0e4b22/ui/com/msg-list/index.jsx), which has become a "workhorse." It's used very frequently, which is good, but it has way too much functionality and needs to be decomposed. (This was one thing my aborted refactor was meant to address.)

[This is the pipeline for messages](https://github.com/ssbc/patchwork/blob/86452344896ffa0c41f1d908e06b08b1ac0e4b22/ui/com/msg-list/index.jsx#L313-L321). Notice that filtering occurs after [`processMsg`](https://github.com/ssbc/patchwork/blob/86452344896ffa0c41f1d908e06b08b1ac0e4b22/ui/com/msg-list/index.jsx#L271-L277), which calls [`u.getPostThread`](https://github.com/ssbc/patchwork/blob/86452344896ffa0c41f1d908e06b08b1ac0e4b22/ui/lib/util.js#L306), which is the source of all the RPC calls you logged.

As far as I remember/can-find, the profile component is the only thing to use the filtering, [here](https://github.com/ssbc/patchwork/blob/86452344896ffa0c41f1d908e06b08b1ac0e4b22/ui/com/user-profile.jsx#L71-L87). (There's a subtle difference in the two filters there, which ought to be highlighted more clearly: one shows encrypted messages, the other shows unencrypted.)

The obvious solution is to move filtering to happen before `processMsg`, so I did that in https://github.com/ssbc/patchwork/pull/76.

**Comment by pfraze** [comment] 2015-11-07 18:47
(This doesn't fix performance. We'll need to do more work reducing RTs.)

**Comment by dominictarr** [comment] 2015-11-08 06:01
The problem isn't round trips, per se, it's that it reads ALL the messages you posted.
If it only read the 30 most recent it would be okay. That works correctly on the main feed, which I think is why that is a reasonable time, but this one isn't.

**Comment by pfraze** [comment] 2015-11-08 06:23
You're right. It should be stopping after 30 good hits, but it's going past that.

Not all the way, though. I have 700 messages published, and this goes to 354. Other feeds have similar result. I think something's wrong with the pull-stream construction in `ui/com/msg-list` `loadMore()`.

**Comment by pfraze** [comment] 2015-11-08 15:55
I did some more logging. I believe it *is* stopping after 30 good hits. The issue is, the filter is so narrowly-defined, it takes a while to find 30.

In the case of my feed, you have to scan 354 messages to find 30 non-reply, unencrypted posts.

**Comment by dominictarr** [comment] 2015-11-09 03:08
I was curious, so I did some experimentation here:
https://gist.github.com/dominictarr/60e3b069858b49e97db2

am I missing something essential that you need to render the posts? Names?
I got 396 ms, which is definately faster what what I was observing in the app.

**Comment by pfraze** [comment] 2015-11-09 04:06
When I log fetch times in #76, I find the loadtime for the newsfeed and profile page are the same. (Can you check that you have the same? I left the logging in there.) This tells me the runtime filtering is not an issue, and that #76 does solve the issue highlighted by this thread: that there was needless work being done on profile views until the filtering was reordered.

The remaining issue is that there are [a lot of RTs after `relatedMessages` in `u.getPostThread`](https://github.com/ssbc/patchwork/blob/filter-before-processing/ui/lib/util.js#L306), and that's what your snippet doesn't include. PW is constructing the full thread for each item in the list. This was done to simplify things during dev. When PW is stabilized, it should be changed to fetch the minimum the list needs, and fetch the full thread only when it's opened.

**Comment by dominictarr** [comment] 2015-11-12 19:30
Okay I think I got it. I tried changing `paramap` (in my code) for `pull.asyncMap` and it slowed down to `~2500` ms from `~350`. try using `paramap` instead?

**Comment by pfraze** [comment] 2015-11-12 19:58
Hmm, I tried that but didn't get any improvement, which is pretty odd, IMO.

I decided to try moving the thread-loading code to *after* the initial render. That showed the kind of speed increased I'd expect, but look how long it takes to load the thread data!

![loadtime](https://cloud.githubusercontent.com/assets/1270099/11129427/dd8e85c2-8944-11e5-98d4-5e10d81c55af.gif)

Cool gif but yeah, that's not right.

This approach is also not able to do filtering on data which gets loaded after rendering, which it needs to do.

The three main things I think need to be done:

 1. Figure out why paramap didnt have an effect for me.
 2. Reduce the amount of data loaded for just the list-view, to the minimum.
 3. Consider precomputing the thread structure in patchwork's API, as a view, so it's only one RT.

**Comment by dominictarr** [comment] 2015-11-13 05:59
Are you sure there isn't another asyncMap happening somewhere? what about refactoring the IO bit out of msg-list and see if we can bench it in isolation.

**Comment by dominictarr** [comment] 2015-11-16 17:08
I took another look at this, and I noticed that you are decrypting all messages before you filter them, even though you only display plaintext messages. skipping, and using paramap that got it to about 500 ms (down from 700).
(I tried putting decryptThread into paramap but that didn't work at all for no obvious reason. That is another bug though.)

In my test script, I switched related messages out for:
```
        paramap(function (data, cb) {
          pull(
            sbot.links({dest: data.key, rel: 'root'}),
            pull.collect(function (err, links) {
              data.replies = links
              cb(null, data)
            })
          )
        }, 16),
        paramap(function (data, cb) {
          pull(
            sbot.links({dest: data.key, rel: 'vote'}),
            pull.collect(function (err, links) {
              data.votes = links
              cb(null, data)
            })
          )
        }, 16)
      )
```

And that took it down to 400 ms (not decrypting)
If you the related message part out entirely, it gets under 200 ms, which is ideally what we want to shoot for, but we sort of need that info, and 400 is acceptable for now.

**Comment by pfraze** [comment] 2015-12-18 02:06
Closing for https://github.com/ssbc/patchwork/issues/173

**Closed by pfraze** 2015-12-18 02:06 UTC
Labels: enhancement
