### ISSUE TITLE
Unexpected Error: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by cryptix** [ssbc/patchwork#46] opened 2015-10-18 13:50 UTC
Appeared after clicking "Flag this post > Spam"

```
TypeError: Cannot read property 'appendChild' of null
    at /home/cryptix/patchwork/ui/lib/com/message.js:197:52
    at Object._requests.(anonymous function) (/home/cryptix/patchwork/node_modules/packet-stream/index.js:37:5)
    at PacketStream._onrequest (/home/cryptix/patchwork/node_modules/packet-stream/index.js:139:26)
    at PacketStream.write (/home/cryptix/patchwork/node_modules/packet-stream/index.js:122:41)
    at /home/cryptix/patchwork/node_modules/muxrpc/pull-weird.js:55:15
    at /home/cryptix/patchwork/node_modules/muxrpc/node_modules/pull-stream/sinks.js:15:33
    at /home/cryptix/patchwork/node_modules/pull-stream/throughs.js:97:9
    at EventEmitter.onincoming (/home/cryptix/patchwork/node_modules/pull-ipc/index.js:54:7)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)

This was an unhandled exception.
```

Ps: I tried it because I posted a dead link but I'm not sure what I would actually trigger..

**Comment by pfraze** [comment] 2015-10-18 19:28
Maybe a duplicate of https://github.com/ssbc/patchwork/issues/35

**Closed** 2015-12-06 04:10 UTC
Labels: bug
