### ISSUE TITLE
Unable to build and run

### ISSUE THREAD

**Issue by sbosshardt** [ssbc/patchwork#617] opened 2017-08-27 01:38 UTC
I checked out tag v3.6.4 and followed the build instructions but cannot start patchwork. `npm install` seems to work fine. There appears to be some missing dependency (xtend/mutable) that causes a runtime error when I `npm start`. I tried newer releases (in case this was fixed) but `npm install` fails.

```
$ npm start

> ssb-patchwork@3.6.4 start /home/sbosshardt/Software/github/ssbc/patchwork
> electron index.js

App threw an error during load
Error: Cannot find module 'xtend/mutable'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/sbosshardt/Software/github/ssbc/patchwork/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/sbosshardt/Software/github/ssbc/patchwork/lib/window.js:3:14)
    at Object.<anonymous> (/home/sbosshardt/Software/github/ssbc/patchwork/lib/window.js:68:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
{ Error: Cannot find module 'xtend/mutable'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/sbosshardt/Software/github/ssbc/patchwork/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/sbosshardt/Software/github/ssbc/patchwork/lib/window.js:3:14)
    at Object.<anonymous> (/home/sbosshardt/Software/github/ssbc/patchwork/lib/window.js:68:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32) code: 'MODULE_NOT_FOUND' }
```

I'm on Linux Mint 18. Versions of node and npm: 
```
$ node --version
v4.8.4
$ npm --version
2.15.11
```

I've tried checking out v3.6.5 and v3.6.6, but I get errors from npm / git when I run "npm install".
````
$ npm install
npm ERR! git rev-list -n1 901c79c841d9a4ee771ce6d9f3951459f8f8079b: fatal: bad object 901c79c841d9a4ee771ce6d9f3951459f8f8079b
npm ERR! git rev-list -n1 901c79c841d9a4ee771ce6d9f3951459f8f8079b: 
npm ERR! git rev-list -n1 901c79c841d9a4ee771ce6d9f3951459f8f8079b: fatal: bad object 901c79c841d9a4ee771ce6d9f3951459f8f8079b
npm ERR! git rev-list -n1 901c79c841d9a4ee771ce6d9f3951459f8f8079b: 
npm ERR! git rev-list -n1 901c79c841d9a4ee771ce6d9f3951459f8f8079b: fatal: bad object 901c79c841d9a4ee771ce6d9f3951459f8f8079b
npm ERR! git rev-list -n1 901c79c841d9a4ee771ce6d9f3951459f8f8079b: 
npm ERR! Linux 4.4.0-87-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.8.4
npm ERR! npm  v2.15.11
npm ERR! code 128

npm ERR! Command failed: git rev-list -n1 901c79c841d9a4ee771ce6d9f3951459f8f8079b
npm ERR! fatal: bad object 901c79c841d9a4ee771ce6d9f3951459f8f8079b
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sbosshardt/Software/github/ssbc/patchwork/npm-debug.log
````

The log that npm asks me to provide is attached.
[npm-debug.log.txt](https://github.com/ssbc/patchwork/files/1254081/npm-debug.log.txt)

**Comment by mmckegg** [comment] 2017-09-30 03:51
@sbosshardt Very strange. Did you ever figure this out? Did you try trashing everything and starting again? 

I think the error when checking out more recent versions has been resolved now. It was caused by a deleted branch.

I'm going to close this issue, but feel free to reopen if you still are having problems!

**Closed by mmckegg** 2017-09-30 03:51 UTC
