### ISSUE TITLE
Windows: Won't load without Internet

### ISSUE THREAD

**Issue by av8ta** [ssbc/patchwork#532] opened 2017-05-08 05:47 UTC
Patchwork won't load if the Internet is disconnected. 

If I connect to the Internet before starting Patchwork it loads just fine and I can disconnect to browse offline no problem. This is on the Windows release. Also all the png's for the emoji are gone (there is no app.asar folder). No idea if that is related!

![not loading](https://cloud.githubusercontent.com/assets/17036768/25791732/54672bfe-3416-11e7-90df-15e416c4c117.PNG)

**Comment by ahdinosaur** [comment] 2017-05-29 10:46
i'm not able to reproduce this. Patchwork loads fine for me without any internet connection.

_but_, sometimes Patchwork does fail to load for me, regardless of my internet connection, i think caused by an error in [`scuttlebot`](https://github.com/ssbc/scuttlebot). maybe this is that? if so, it should work after closing and restarting Patchwork.

is anyone else able to reproduce this reliably?

**Comment by mmckegg** [comment] 2017-05-29 22:31
I have noticed that if at any point you click on a link to a "missing message" that I get this loading problem and then nothing else will ever load again. Have to restart.

Could be related? An error occurs, and then sbot communication breaks. This shouldn't be the case.

**Comment by mmckegg** [comment] 2017-05-29 22:33
Oh, the error that @av8ta is reporting is because github can't be connected to for updating checking. This shouldn't affect anything else though.

Is this patchwork **3.4.0**? Maybe we broke the emoji symlink.

**Comment by av8ta** [comment] 2017-05-31 05:37
It was windows 3.3.0 release. 
Tried it on 3.3.0 and 3.4.0 release binaries. Both are the same - won't load without the Internet when patchwork boots.
Built the latest version today on windows and linux. I have the same problem on windows. Everything is fine on linux.
Emojis are working on linux :+1: 

Is this a windows thing?

**Comment by clehner** [comment] 2017-06-02 23:19
> I have noticed that if at any point you click on a link to a "missing message" that I get this loading problem and then nothing else will ever load again. Have to restart.
> 
> Could be related? An error occurs, and then sbot communication breaks. This shouldn't be the case.

This may because patchcore checks for NotFoundError in response to sbot.get, but with flumeview-level@2.0.1, that error is wrapped and does not match the check, so the error is not handled properly. With flumeview-level@2.0.2 (https://github.com/flumedb/flumeview-level/pull/1) the NotFoundError is back, so the old behavior should work again.

**Comment by mmckegg** [comment] 2017-06-27 01:32
Emojis are symlinked into an internal node_module. Windows isn't very symlink friendly. I have to manually copy them over when I do a windows build and sometimes I forget. 

I have also encountered this "doesn't load when not connected to the internet" issue. I wonder what could cause that!? Will investigate.

**Closed** 2017-06-30 12:20 UTC
Labels: bug

**Comment by av8ta** [comment] 2017-07-18 00:08
@mmckegg this problem has gone away since installing windows release 3.6.5, thanks :)
