### ISSUE TITLE
stream is closed

### ISSUE THREAD

**Issue by bhaugen** [ssbc/patchwork#287] opened 2016-02-04 20:42 UTC
stream is closed

This was an unhandled exception.

```
createMuxrpc/emitter<@http://localhost:7777/main.build.js:23:20584
remoteCall@http://localhost:7777/main.build.js:23:19213
recurse/</obj[name]<@http://localhost:7777/main.build.js:23:19487
["/Users/paulfrazee/patchwork/ui/lib/mentions.js"]</exports.extract@http://localhost:7777/main.build.js:56:1893
onSend@http://localhost:7777/main.build.js:47:31225
invokeGuardedCallback@http://localhost:7777/main.build.js:38:2360
executeDispatch@http://localhost:7777/main.build.js:33:2502
executeDispatchesInOrder@http://localhost:7777/main.build.js:33:3005
["/Users/paulfrazee/patchwork/node_modules/react/lib/EventPluginHub.js"]</executeDispatchesAndRelease@http://localhost:7777/main.build.js:32:23122
["/Users/paulfrazee/patchwork/node_modules/react/lib/EventPluginHub.js"]</executeDispatchesAndReleaseTopLevel@http://localhost:7777/main.build.js:32:23399
["/Users/paulfrazee/patchwork/node_modules/react/lib/forEachAccumulated.js"]</forEachAccumulated@http://localhost:7777/main.build.js:42:11817
["/Users/paulfrazee/patchwork/node_modules/react/lib/EventPluginHub.js"]</EventPluginHub.processEventQueue@http://localhost:7777/main.build.js:32:26446
runEventQueueInBatch@http://localhost:7777/main.build.js:38:3490
["/Users/paulfrazee/patchwork/node_modules/react/lib/ReactEventEmitterMixin.js"]</ReactEventEmitterMixin.handleTopLevel@http://localhost:7777/main.build.js:38:3774
handleTopLevelWithoutPath@http://localhost:7777/main.build.js:38:5677
handleTopLevelImpl@http://localhost:7777/main.build.js:38:5237
["/Users/paulfrazee/patchwork/node_modules/react/lib/Transaction.js"]</Mixin.perform@http://localhost:7777/main.build.js:42:3463
["/Users/paulfrazee/patchwork/node_modules/react/lib/ReactDefaultBatchingStrategy.js"]</ReactDefaultBatchingStrategy.batchedUpdates@http://localhost:7777/main.build.js:37:5622
batchedUpdates@http://localhost:7777/main.build.js:40:28846
["/Users/paulfrazee/patchwork/node_modules/react/lib/ReactEventListener.js"]</ReactEventListener.dispatchEvent@http://localhost:7777/main.build.js:38:8105
```

**Comment by bhaugen** [comment] 2016-02-04 20:43
But it was nice that the error message offered to file an issue for me. Adding the details for me would have been even nicer...

**Comment by pfraze** [comment] 2016-02-04 21:20
> But it was nice that the error message offered to file an issue for me. Adding the details for me would have been even nicer...

I figure, hey, having an issue sucks enough already.

Is it possible the server had been closed? If so, this issue may actually be a duplicate of https://github.com/ssbc/patchwork/issues/255

**Comment by bhaugen** [comment] 2016-02-04 21:26
Probably. I had stopped the server to check something, then restarted it, but had not reloaded the page before entering a reply. You can mark it a dup.

**Comment by pfraze** [comment] 2016-02-04 21:28
Cool

**Closed by pfraze** 2016-02-04 21:28 UTC
Labels: bug
