### ISSUE TITLE
Module version mismatch. Expected 46, got 47.

### ISSUE THREAD

**Issue by sartaj** [ssbc/patchwork#215] opened 2015-12-22 07:59 UTC
Got this error on both the npm install and an git install.
` node v5.0.0`
`ssb-patchwork@2.0.5`

```
0 info it worked if it ends with ok
1 verbose cli [ '~/.nvm/versions/node/v5.0.0/bin/node',
1 verbose cli   '~/.nvm/versions/node/v5.0.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ssb-patchwork@2.0.5~prestart: ssb-patchwork@2.0.5
6 silly lifecycle ssb-patchwork@2.0.5~prestart: no script for prestart, continuing
7 info lifecycle ssb-patchwork@2.0.5~start: ssb-patchwork@2.0.5
8 verbose lifecycle ssb-patchwork@2.0.5~start: unsafe-perm in lifecycle true
9 verbose lifecycle ssb-patchwork@2.0.5~start: PATH: ~/.nvm/versions/node/v5.0.0/lib/node_modules/npm/bin/node-gyp-bin:~/clients/ssbc/patchwork/node_modules/.bin:~/.nvm/versions/node/v5.0.0/bin:~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle ssb-patchwork@2.0.5~start: CWD: ~/clients/ssbc/patchwork
11 silly lifecycle ssb-patchwork@2.0.5~start: Args: [ '-c', 'electron .' ]
12 silly lifecycle ssb-patchwork@2.0.5~start: Returned: code: 7  signal: null
13 info lifecycle ssb-patchwork@2.0.5~start: Failed to exec start script
14 verbose stack Error: ssb-patchwork@2.0.5 start: `electron .`
14 verbose stack Exit status 7
14 verbose stack     at EventEmitter.<anonymous> (~/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/utils/lifecycle.js:233:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (~/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid ssb-patchwork@2.0.5
16 verbose cwd ~/clients/ssbc/patchwork
17 error Darwin 15.2.0
18 error argv "~/.nvm/versions/node/v5.0.0/bin/node" "~/.nvm/versions/node/v5.0.0/bin/npm" "start"
19 error node v5.0.0
20 error npm  v3.3.6
21 error code ELIFECYCLE
22 error ssb-patchwork@2.0.5 start: `electron .`
22 error Exit status 7
23 error Failed at the ssb-patchwork@2.0.5 start script 'electron .'.
23 error This is most likely a problem with the ssb-patchwork package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron .
23 error You can get their info via:
23 error     npm owner ls ssb-patchwork
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by pfraze** [comment] 2015-12-22 15:04
This has to do with the electron version we use being incompatible with node v5. Use node v4 for now. We have a PR pending to fix this.

**Comment by pfraze** [comment] 2015-12-22 15:04
Sorry for the trouble! Closing as a duplicate of https://github.com/ssbc/patchwork/issues/129

**Closed by pfraze** 2015-12-22 15:04 UTC
