### ISSUE TITLE
error loading sodium bindings

### ISSUE THREAD

**Issue by rdbartlett** [ssbc/patchwork#861] opened 2018-10-01 16:34 UTC
Just installed the latest Patchwork on my mac. Had to reload a few times before it worked (was getting stuck in scuttling state). Now it is working, but I see this in my console, so I'm sharing in case it is useful:

![image](https://user-images.githubusercontent.com/970124/46302118-f0394080-c5b0-11e8-833c-3e80d918ff10.png)

**Comment by christianbundy** [comment] 2018-10-01 16:41
Thanks @rdbartlett! This is super useful for debugging the issue. If we get a potential fix together would you be available to test it before the actual realease?

@mmckegg I saw that Sharp had a similar issue with Electron packages. If you're interested, here's their workaround: https://github.com/lovell/sharp/issues/678#issuecomment-275956028. Maybe we could do the same with libsodium, is [patchwork-builder](https://github.com/ssbc/patchwork-builder) still being used for Patchwork releases?

**Comment by marlun** [comment] 2018-10-13 17:28
I'm also getting "error loading sodium bindings" when I open Patchwork from the terminal on OSX and it gets stuck on "Scuttling..."/"Loading...". I just upgraded from maybe a 4-5 old version to 3.11.2.

**Comment by cryptix** [comment] 2018-10-13 19:28
If you installed from source, you should be able to run `npm run rebuild` to get it built.

**Comment by mmckegg** [comment] 2018-10-13 20:19
@rdbartlett @marlun are you both running the AppImage on Linux?

I haven’t tested the appimage build for some time. Maybe it’s broken? I don’t have a GUI Linux machine at the moment.

**Comment by marlun** [comment] 2018-10-13 20:38
@mmckegg I'm running it on my Mac (Patchwork-3.11.2-mac.dmg) and so does @rdbartlett it seems (from his message).

**Comment by cinnamon-bun** [comment] 2018-11-03 16:38
Still getting this in 3.11.3.  Starting from the terminal I see:
```
error loading sodium bindings: dlopen(/var/folders/1t/w6lhrhk13w5fn7_f2bwz78380000gn/T/.org.ssbc.patchwork.v3yqo0, 1): Library not loaded: @loader_path/libsodium.dylib
  Referenced from: /var/folders/1t/w6lhrhk13w5fn7_f2bwz78380000gn/T/.org.ssbc.patchwork.v3yqo0
  Reason: image not found
falling back to javascript version.
```

OSX 10.11.6

**Comment by mmckegg** [comment] 2018-12-03 05:19
I think the error message might have been caused by a broken build. That message is most likely not the reason that patchwork is not running.

There is an issue in the current releases 3.11.x where they get stuck on startup if you try and run patchbay on the same machine (one at a time). The cure is just to wait a while with the _scuttling_ spinners (around 2 mins), and then restart  (the indexes are completing in the background, but for some reason patchwork does not load when they complete).

Anyway, next release of patchwork should fix this, so I'm going to close this issue. Feel free to open if the problem re-appears.

**Closed by mmckegg** 2018-12-03 05:19 UTC
Labels: bug, builds, macOS
