### ISSUE TITLE
No emojis being displayed

### ISSUE THREAD

**Issue by PARC6502** [ssbc/patchwork#1080] opened 2019-06-10 10:59 UTC
I think this is a separate issue to [this](https://github.com/ssbc/patchwork/issues/1062) as none of my emojis are displaying, this is what I see

![image](https://user-images.githubusercontent.com/3056543/59191002-297d7380-8b76-11e9-8841-1ea60a2c8ded.png)

When I inspect element and click on the  url for the emoji I see something like this: `file:///C:/[...]/Programs/ssb-patchwork/resources/app.asar/assets/img/emoji/closed_lock_with_key.png`

**Comment by christianbundy** [comment] 2019-06-10 15:42
Hey, thanks for the bug report! I think this is a duplicate of https://github.com/ssbc/patchwork/issues/1053, could you try the latest release? I've just pushed the code, and an installer should be available on the [release page](https://github.com/ssbc/patchwork/releases) within the hour.

**Closed** 2019-06-10 17:23 UTC
Labels: duplicate, type:bug

**Comment by PARC6502** [comment] 2019-06-11 09:58
Sorry I didn't see the other issue, the new release has fixed it!
