### ISSUE TITLE
"Bookmarked" not loading

### ISSUE THREAD

**Issue by cryptix** [ssbc/patchwork#234] opened 2016-01-04 16:44 UTC
It just stays like this:

![notloading](https://cloud.githubusercontent.com/assets/111202/12094552/63c7aae0-b309-11e5-92e9-fdc0fd5b468b.png)

According to `git revlog`, I was using 1010a05 before. I rolled back and reinstalled that version, but the bookmarks are also blocked there now...

**Comment by pfraze** [comment] 2016-01-04 16:53
Ok thanks. Nothing in your console, right?

**Comment by cryptix** [comment] 2016-01-04 17:10
Not as far as I can tell.

ps: it would help if we could de-noise the embedded `sbot` output.

**Comment by pfraze** [comment] 2016-01-04 17:11
Yeah, we ought to put the logging behind a `-verbose` flag or something

**Comment by pfraze** [comment] 2016-01-17 00:35
@cryptix is this still happening on latest?

**Comment by cryptix** [comment] 2016-01-19 10:06
just regained access to that installation aaand It's still happening... :-/

I see that it is hard to reproduce. Can you think of a trick to kick it back into working?
How would i clean the `.ssb` folder to re-sync it from the network? Do I need more than the `.ssb/secret` file?

**Comment by pfraze** [comment] 2016-01-19 15:44
No dont do that, this shouldnt be a data corruption issue. Have you ever bookmarked anything? Try bookmarking something else and see if that solves it.

**Comment by pfraze** [comment] 2016-01-19 15:56
Oh yeah, you've clearly bookmarked some things...

**Comment by pfraze** [comment] 2016-01-19 15:56
I wonder if the problem is the *lack* of bookmarks. I'll try to setup a test case in a bit

**Comment by cryptix** [comment] 2016-02-14 16:24
It's still a thing. I used *Mark all as Read* and the count went from 6 or 7 down to one. I wonder if it is a missing post?

**Comment by pfraze** [comment] 2016-02-14 16:56
I wonder that too, though Im not sure how you could bookmark a post that you dont have.

**Comment by mmckegg** [comment] 2016-10-30 01:00
Bookmarks no longer exist in the current release. Closing.

**Closed by mmckegg** 2016-10-30 01:00 UTC
Labels: bug
