### ISSUE TITLE
Post not loading causing breakage

### ISSUE THREAD

**Issue by clehner** [ssbc/patchwork#169] opened 2015-12-09 16:52 UTC
When I visit the post `%iZk0Xcf3mZ1i4ZUJSYMU6/1LJgU4vP5IXSFUt5L9Vcc=.sha256` or click this comment:
![2015-12-09-114801_264x112_scrot](https://cloud.githubusercontent.com/assets/95347/11691808/b83f0540-9e6a-11e5-9c58-3735250eeae8.png),
I get this error appearing in the left sidebar, and after that posts no longer load and I have to restart patchwork.

```
Cannot read property 'link' of null

TypeError: Cannot read property 'link' of null
    at insertReply (/usr/local/src/patchwork/node_modules/patchwork-threads/index.js:82:46)
    at flattenAndReorderReplies (/usr/local/src/patchwork/node_modules/patchwork-threads/index.js:113:7)
    at Array.forEach (native)
    at Object.exports.flattenThread (/usr/local/src/patchwork/node_modules/patchwork-threads/index.js:72:11)
    at /usr/local/src/patchwork/ui/com/msg-thread.jsx:56:25
    at /usr/local/src/patchwork/node_modules/patchwork-threads/index.js:231:7
    at /usr/local/src/patchwork/node_modules/multicb/index.js:40:13
    at /usr/local/src/patchwork/node_modules/patchwork-threads/index.js:258:25
    at /usr/local/src/patchwork/node_modules/multicb/index.js:40:13
    at /usr/local/src/patchwork/node_modules/patchwork-threads/index.js:299:7

This was an unhandled exception.
```

**Comment by cryptix** [comment] 2015-12-09 16:58
Duplicate of #166. I'm very sorry about this.. >_<

**Comment by pfraze** [comment] 2015-12-09 17:01
Nah dont worry about it. This is a bug in my code -- it should be prepared for mistakes in the message structures.

**Closed by pfraze** 2015-12-09 17:01 UTC

**Comment by clehner** [comment] 2015-12-09 17:06
Thanks for catching that. I should have checked for an existing issue more closely
