### ISSUE TITLE
Cannot read property 'link' of null

### ISSUE THREAD

**Issue by jrf0110** [ssbc/patchwork#168] opened 2015-12-09 15:11 UTC
Cannot read property 'link' of null

I thought this was a bad merge on my command palette branch, but I checked out master, pulled the latest, `rm -rf`'d my `node_modules/` and npm installed.

TypeError: Cannot read property 'link' of null
    at insertReply (/Users/john/random-repos/patchwork/node_modules/patchwork-threads/index.js:82:46)
    at flattenAndReorderReplies (/Users/john/random-repos/patchwork/node_modules/patchwork-threads/index.js:113:7)
    at Array.forEach (native)
    at Object.exports.flattenThread (/Users/john/random-repos/patchwork/node_modules/patchwork-threads/index.js:72:11)
    at /Users/john/random-repos/patchwork/ui/com/msg-thread.jsx:56:25
    at /Users/john/random-repos/patchwork/node_modules/patchwork-threads/index.js:231:7
    at /Users/john/random-repos/patchwork/node_modules/multicb/index.js:40:13
    at /Users/john/random-repos/patchwork/node_modules/patchwork-threads/index.js:258:25
    at /Users/john/random-repos/patchwork/node_modules/multicb/index.js:40:13
    at /Users/john/random-repos/patchwork/node_modules/patchwork-threads/index.js:299:7
```

This was an unhandled exception.

It happens when trying to click a link in my notifications area

**Comment by pfraze** [comment] 2015-12-09 15:20
Thanks for the report, this is a duplicate of https://github.com/ssbc/patchwork/issues/166

**Closed by pfraze** 2015-12-09 15:20 UTC
