### ISSUE TITLE
Please avoid the setuid chome-sandbox

### ISSUE THREAD

**Issue by madduck** [ssbc/patchwork#1236] opened 2020-01-09 07:59 UTC
I can start an AppImage of Patchwork as non-root, so I don't understand why the Debian packaged version requires a setuid-root `chrome-sandbox`. Especially since I must assume that this is a Google-provided binary, there is no way I will give root permissions to this code.

**Comment by black-puppydog** [comment] 2020-01-11 04:03
that's a huge (and ongoing?) discussion: https://github.com/electron/electron/issues/17972
I don't think anyone's really happy about the situation...

**Comment by black-puppydog** [comment] 2020-01-11 04:10
Actually I'd say we close this as duplicate of #1217 and rename that one to be more informative.

**Comment by christianbundy** [comment] 2020-01-11 21:41
Sorry you're bumping into this too @madduck. Please see [Patchwork's documentation on the sandbox problem](https://github.com/ssbc/patchwork/blob/master/docs/INSTALL.md#sandbox) and feel free to chime in with potential solutions in #1217. I'd love all the help we can get.

**Closed by christianbundy** 2020-01-11 21:41 UTC

**Comment by madduck** [comment] 2020-01-11 23:57
Thanks guys!
