### ISSUE TITLE
Opening a blob link in browser, "unable to connect"

### ISSUE THREAD

**Issue by myself248** [ssbc/patchwork#992] opened 2019-04-17 08:34 UTC
When clicking a blob link in Patchwork, Firefox opens a new tab pointing at http://localhost:8989/blobs/get/whateverblobstringhere but simply complains "unable to connect".

I'm running the 3.11.6 appimage on ubuntu. Is there any more data I should provide?

**Comment by gergelypolonkai** [comment] 2019-04-17 10:18
I can’t reproduce it on Arch nor on Fedora, neither with the AppImage nor with the AUR package. Does the problem persist if you restart Patchwork? Sounds like `ssb-server` is not listening on port 8989 for some reason.

**Comment by myself248** [comment] 2019-04-17 11:48
Persists after restarting Patchwork, persists after rebooting the whole machine. 

I still had Patchwork-3.11.4-linux-x86_64.AppImage sitting in my Downloads so I tried running that, and it works! I can finally see Luandro's solar controller. ;) I closed 3.11.4 and relaunched 3.11.6 and it's back to not working. Did this twice and the problem follows the version.

While running 3.11.6, the output of netstat | grep "8989" is null. 

nmap localhost -p 8989 reports the port is "closed".

While running 3.11.4, the output of netstat | grep "8989"
tcp6       0      0 localhost:8989          localhost:35332         TIME_WAIT  

nmap localhost -p 8989 reports the port is "open".

**Comment by christianbundy** [comment] 2019-04-17 16:34
@myself248 Could you try the code in `master` to see if the issue is resolved? I'm wondering whether this issue was resolved in a dependency (https://github.com/ssbc/multiserver/pull/44).

**Comment by myself248** [comment] 2019-04-17 22:27
I'm not sure how to be sure I'm getting "master", but I followed the git clone instructions on the main page and I have a lovely new thing that identifies itself as "Patchwork 3.12.0-dev", and blob links work just fine now.

**Comment by christianbundy** [comment] 2019-04-17 23:18
Yep, you got it! It sounds like the problem has been resolved, thanks a lot for taking the time to debug. I'm working on releasing a new version with that fix (see #994), are you alright using 3.12.0-dev for the time being?

**Comment by myself248** [comment] 2019-04-18 00:54
Seems to be working so far, and if I have trouble I can always go back to the last release and just miss out on blobs. All good, thank you!

**Comment by christianbundy** [comment] 2019-04-18 02:01
Sweet, thanks for reporting this -- please reach out if you notice any strange behavior on `master`, otherwise look forward to a new version being released soon!

**Closed by christianbundy** 2019-04-18 02:01 UTC
Labels: bug
