### ISSUE TITLE
patchwork name is confusing

### ISSUE THREAD

**Issue by anarcat** [ssbc/patchwork#467] opened 2017-04-07 03:43 UTC
hi!

i am a little confused by the name "patchwork" - in my mind, it is a patch review software, mailing-list based, and not a SSB app. you can see more information about that other project on their [homepage](http://jk.ozlabs.org/projects/patchwork/). that patchwork has been in activity since [at least 2008](https://lists.ozlabs.org/pipermail/patchwork/2008-September/000000.html)...

should this patchwork be renamed somehow? is it a temporary name or the real thing? at the very least, it may cause conflicts when / if this is packaged for debian, although the other package is still at the [planning stage](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=703226), package-wise...

really interesting project, can't want to try it out more widely. :)

**Comment by mmckegg** [comment] 2017-04-07 03:49
Totally agree!

But as to why, the easy answer is that **names are hard**.

If a new name falls out of the sky, I'd be keen to run with it. But for now, eh, kind of fits the subjective model of SSB having a name that is used for something else 😉 

If we renamed IMO we'd need to check all these boxes:
- [ ] something easy spell and pronounce (in multiple languages)
- [ ] nothing else with high google ranking with the same name
- [ ] some kind of clever pun or reference to off-grid, sailing, decentralized, hermit crabs, etc

**Comment by anarcat** [comment] 2017-04-07 03:52
sorry for opening that can of worms, btw - but i figured it was worth mentioning... i'll try to contribute ideas in exchange for my boldness when they cross my brain. :)

**Comment by anarcat** [comment] 2018-11-10 17:01
wait, why was this closed again? just because it was stale?? do we need to just constantly ping issues every 9 days to keep something opened here?

**Comment by christianbundy** [comment] 2018-11-10 17:16
Hey @anarcat, sorry that this issue was closed. We had more issues than we could take care of so many/most were ignored, so I went through and closed out issues that had no activity for months. 

Full discussion here: `%jn8ZQC3f6gCyuZFpA3uBNF5Nw6/LtXVYwpzV1sko6OA=.sha256`, but the gist is that we had so many open issues that they were just getting ignored. I'm really trying to work through the issue backlog, and one aspect of that was warning and closing issues that are inactive (and often irrelevant). I'd love your feedback on the above thread if you have suggestions on how to improve this process.

**Comment by SquidLord** [comment] 2018-11-10 18:05
> I'd love your feedback on the above thread if you have suggestions on how to improve this process.

I have a pretty good one.

Take action on things in a timely manner.

That's not to say that something needs to be solved immediately. Some problems are hard and some problems are not as high-priority as others. Problems and issues can linger for quite a while.

But irrelevant things are relevant from the beginning. If there are issues that need to be addressed, acknowledge that they are being worked on and leave the issue – because it has been adjudged to be a real thing.

Likewise, if something is irrelevant, say-so and then close the issue. Don't let it be in the list if it's not relevant.

Don't let a bot do the job of a developer.

Every once in a while it's necessary to go through and garbage collect issues. I know things can pile up. But the way to do that is to budget some time to manually do that, and when you summarily close something – say why. It's the same reason that we demand that code be commented so that other people understand why a thing is being done in a certain way. Github is just the code which supports the infrastructure of the process of writing and maintaining software. As such, it needs a dedication to comment and maintenance as much as any other part of the code.

**Comment by swedebugia** [comment] 2018-11-18 13:34
I propose: **scuttlesailor**
Searching with duckduck I get:
Not many results contain scuttlesailor. Search only for "scuttlesailor"? and the first results are totally unrelated to software :)
https://duckduckgo.com/?t=palemoon&q=scuttlesailor&ia=web

**Comment by qbolec** [comment] 2018-12-08 22:16
https://en.wikipedia.org/wiki/Anomura ?
As in: I was anomured by her:)

**Comment by mmckegg** [comment] 2018-12-09 02:17
Hey, thanks everyone for the input. I've had a change of heart since April 2017 when I said that I wanted to change the name. 

It's too late and too established now. Nothing else will sound right. If it bothers you, make a new client and call it whatever you want. This is the wonderful world of subjective scuttlebutt --- they're all "official" clients!

IMO the current name is fine in every way except that there are quite a few other projects with the same name. But this doesn't really bother me, this isn't a corporate product that needs a strong brand, it's just little ol' patchwork.

I'm going to close this.

**Closed by mmckegg** 2018-12-09 02:17 UTC
Labels: discussion, enhancement, help wanted

**Comment by mmckegg** [comment] 2018-12-09 02:18
Oh if you need to disambiguate in a package manager, I hear-by designate `ssb-patchwork`!
