### ISSUE TITLE
Patchwork starts with error always

### ISSUE THREAD

**Issue by mafintosh** [ssbc/patchwork#431] opened 2016-11-29 07:49 UTC
Using latest master with a fresh npm install I keep getting this error.

![screen shot 2016-11-29 at 04 47 19](https://cloud.githubusercontent.com/assets/376661/20700953/1da1ac66-b5ef-11e6-95f1-579bcfef32b7.png)

Any help would be appreciated so I can get back online :)

**Comment by ahdinosaur** [comment] 2016-11-29 08:10
hey @mafintosh,

sorry to hear you're having an error. hmm. i can't reproduce at the moment. only possible advice i can think of right now is to run `npm run build`.

in the meantime, if you're okay with Electron, you can also try:

- [`patchwork-electron`](https://github.com/ssbc/patchwork-electron/releases/tag/v2.12.3) (this repository built into a standalone electron release), 
- [`patchwork-next`](https://github.com/mmckegg/patchwork-next) (a work-in-progress successor to Patchwork classic built using Patchbay),
- or [`patchbay`](https://github.com/dominictarr/patchbay) (an unopinionated and pluggable interface).

**Comment by mafintosh** [comment] 2016-11-29 08:17
Building again didnt work.
I'll try the electron one on my next layover :)

**Comment by dominictarr** [comment] 2016-11-29 12:39
that is a content security policy error.

why is it trying to connect to example.com??? that is really weird

**Comment by mafintosh** [comment] 2016-11-29 13:22
Yea. Anything I can do to help debug? Trying the electron version now

**Comment by staltz** [comment] 2016-12-01 13:31
Also getting problems, with `patchwork`:

![screen shot 2016-12-01 at 15 28 38](https://cloud.githubusercontent.com/assets/90512/20795638/dd00eb5c-b7da-11e6-91d1-7b65b1382f68.png)

And with `patchwork-electron`:

![screen shot 2016-12-01 at 15 29 58](https://cloud.githubusercontent.com/assets/90512/20795681/0929b9e8-b7db-11e6-86b5-c86aa959a876.png)

Patchwork-next worked, but so far it's too limited, I can't even join pubs, so I'm limited to talking to myself.

**Comment by mmckegg** [comment] 2016-12-01 15:57
@staltz there is a workaround in the current patchwork-next version that lets you connect to pubs.

Type `/setup` into the search box, and it brings up the patchbay onboarding screen.

But yes, nice onboarding pretty high on the priority list to get done in "next". Would be nice to fix the patchwork "classic" bugs too though 😆

**Comment by dominictarr** [comment] 2016-12-01 15:58
my guess is it's something about patchwork's in memory indexes, since those get pretty big...

**Comment by ahdinosaur** [comment] 2016-12-02 00:45
@staltz darn. you should also be able to [join a pub](http://scuttlebot.io/docs/social/join-a-pub.html) from the command-line using

```shell
sbot invite.accept {code}
```

while also in a separate terminal running

```shell
sbot server
```

where `sbot` is the command available from a global install of [`scuttlebot`](https://github.com/ssbc/scuttlebot).

**Comment by mmckegg** [comment] 2016-12-13 23:39
https://github.com/jhiesey/stream-http/pull/61 fixes it for me :)

**Comment by Max-Github** [comment] 2016-12-16 08:19
Having the same issue when using Chrome, Chromium and Opera. It works with Firefox though.

**Comment by ahdinosaur** [comment] 2017-03-16 12:26
we just released a new major version: [`v3`](https://github.com/ssbc/patchwork/releases). :sparkles: 

the `ssb-patchwork` npm package is not updated since we're building an electron app, but am still going to close this for now. anyone feel free to open another issue if something comes up!

**Closed by ahdinosaur** 2017-03-16 12:26 UTC
